### ISSUE TITLE
39P 구매 거래 처리 예시 중 "판매 데이터" 부분

### ISSUE THREAD

**Issue by mindock** [KimVanPark/ReadBook#1]
**판매 데이터** : 회사는 지역별로 구매 항목을 추적해 특정 지역에서 어떤 항목이 더 인기 있는지 파악하려고 한다. 목표는 해당 지역의 베스트셀러 품목에 대해 할인과 특가를 제공하는 것이다.

해당 부분은 실시간으로 제공하는 것보다는 데이터를 쌓아서 처리하는 배치성에 더 가까운 부분이 아닐까??

**Comment by vsh123** [comment]
물론 1시간 단위 배치를 통해 랭킹을 업데이트하는 걸 원하는 것도 있겠지만,
실시간으로 랭킹을 업데이트 시키고 싶어하는 니즈도 있을 것 같아요.
