### ISSUE TITLE
p36 복제를 사용해 실패를 수용

### ISSUE THREAD

**Issue by hyelin0111** [KimVanPark/ReadBook#4]
- 다른 서버에 데이터 블록을 복제하기 때문에 더 이상 디스크 오류나 프로덕션을 중단시키는 전체 서버 오류조차 걱정을 할 필요가 없음 <- 뭔 소리야.............?

**Comment by vsh123** [comment]
[반선호의 정리](https://github.com/KimVanPark/ReadBook/wiki/1%EC%A3%BC%EC%B0%A8-%EC%8A%A4%ED%84%B0%EB%94%94#%EB%B0%98%EC%84%A0%ED%98%B8-1)를 참고하세요!
