### ISSUE TITLE
85p 컨슈머와 파티션

### ISSUE THREAD

**Issue by mindock** [KimVanPark/ReadBook#9]
```
일반적으로 토픽의 각 파티션마다 하나씩여러 컨슈머 인스턴스가 필요할 것이다. 
한 컨슈머가 여러 파티션에서 읽도록 할 수 있지만, 파티션 수만큼 스레드 풀에 스레드가 있는 컨슈머가 하나의 파티션에 배정되는 것이 일반적이지는 않다.

이 파티션당 컨슈머 패턴은 처리량을 최대화했지만, 여러 애플리케이션이나 머신에 컨슈머를 분산하는 경우 모든 인스턴스의 총 스레드 수는 해당 토픽의 총 파티션 수를 넘지 않아야 한다.
전체 파티션 수를 초과하는 스레드는 유후 상태가 되기 때문이다. 
컨슈머가 실패하면 리더 브로커는 파티션을 다른 활성 컨슈머에게 할당한다.
```

이해가 잘안돼요...

**Comment by vsh123** [comment]
@vsh123 알아오세요

**Comment by vsh123** [comment]
![image](https://user-images.githubusercontent.com/32254689/124761156-7659f100-df6c-11eb-921b-1c95f09eff6d.png)


이미지 출처 : https://engkimbs.tistory.com/691

`일반적으로 토픽의 각 파티션마다 하나씩여러 컨슈머 인스턴스가 필요할 것이다. `

> 위 이미지에서 첫번째 케이스를 이야기 하는 것 같아요

`한 컨슈머가 여러 파티션에서 읽도록 할 수 있지만, 파티션 수만큼 스레드 풀에 스레드가 있는 컨슈머가 하나의 파티션에 배정되는 것이 일반적이지는 않다.`

> 이건 두번째 상황을 이야기하는데, 이건 아직도 이해가 안감..... 

`이 파티션당 컨슈머 패턴은 처리량을 최대화했지만, 여러 애플리케이션이나 머신에 컨슈머를 분산하는 경우 모든 인스턴스의 총 스레드 수는 해당 토픽의 총 파티션 수를 넘지 않아야 한다. 전체 파티션 수를 초과하는 스레드는 유후 상태가 되기 때문이다.`

> 이미지의 세번째 상황을 이야기하고, 이 컨슈머 서버가 별다른 이 토픽 컨슘말고 다른 작업을 하지 않는다면 C4는 파티션이 신규 생성되기 전까지는 아무것도 안하는(날로먹는) 상황이 발생한다라는 걸 이야기하고 싶었던듯..?
